version: '3'
services:
  app:
    build: ./target
    image: docker-try-fastapi-app
    container_name: docker-try-fastapi-app-cnt
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - ./target/src:/app/src
    environment:
      PYTHONPATH: "/app/src"
      TZ: Asia/Tokyo
    ports:
      - 80:80
